/**
 * TIcon 图标分类常量
 * @description lucide-vue-next 图标分类配置
 */

import type { IconCategory } from './types'

/**
 * 图标分类映射表
 * @description 按 lucide 官方分类整理的图标名称列表
 */
export const ICON_CATEGORIES: IconCategory[] = [
  {
    key: 'arrows',
    name: '箭头',
    icons: [
      'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight',
      'ArrowUpLeft', 'ArrowUpRight', 'ArrowDownLeft', 'ArrowDownRight',
      'ChevronUp', 'ChevronDown', 'ChevronLeft', 'ChevronRight',
      'ChevronsUp', 'ChevronsDown', 'ChevronsLeft', 'ChevronsRight',
      'CornerUpLeft', 'CornerUpRight', 'CornerDownLeft', 'CornerDownRight',
      'CornerLeftUp', 'CornerLeftDown', 'CornerRightUp', 'CornerRightDown',
      'ArrowLeftCircle', 'ArrowRightCircle', 'ArrowUpCircle', 'ArrowDownCircle',
      'ArrowLeftSquare', 'ArrowRightSquare', 'ArrowUpSquare', 'ArrowDownSquare',
      'ArrowBigUp', 'ArrowBigDown', 'ArrowBigLeft', 'ArrowBigRight',
      'ArrowBigUpDash', 'ArrowBigDownDash', 'ArrowBigLeftDash', 'ArrowBigRightDash',
      'Move', 'MoveUp', 'MoveDown', 'MoveLeft', 'MoveRight',
      'MoveDiagonal', 'MoveDiagonal2', 'MoveHorizontal', 'MoveVertical',
      'ArrowUpFromLine', 'ArrowDownFromLine', 'ArrowLeftFromLine', 'ArrowRightFromLine',
      'ArrowUpToLine', 'ArrowDownToLine', 'ArrowLeftToLine', 'ArrowRightToLine',
      'ArrowUpFromDot', 'ArrowDownFromDot', 'ArrowLeftFromDot', 'ArrowRightFromDot',
      'ArrowUpNarrowWide', 'ArrowUpWideNarrow', 'ArrowDownNarrowWide', 'ArrowDownWideNarrow',
      'ArrowUpAZ', 'ArrowUpZA', 'ArrowDownAZ', 'ArrowDownZA',
      'ArrowUp01', 'ArrowUp10', 'ArrowDown01', 'ArrowDown10',
      'ArrowLeftRight', 'ArrowUpDown', 'ArrowsUpFromLine',
      'Redo', 'Redo2', 'Undo', 'Undo2', 'RotateCcw', 'RotateCw',
      'RefreshCcw', 'RefreshCw', 'Repeat', 'Repeat2', 'Reply', 'ReplyAll',
      'Forward', 'StepBack', 'StepForward', 'SkipBack', 'SkipForward',
      'SkipForward', 'SkipBack', 'Play', 'Pause', 'Square', 'Circle',
      'Triangle', 'Diamond', 'Octagon', 'Hexagon', 'Pentagon', 'Star',
      'Heart', 'X', 'Check', 'Plus', 'Minus', 'Divide', 'Percent',
      'Equal', 'NotEqual', 'GreaterThan', 'LessThan', 'GreaterThanOrEqual',
      'LessThanOrEqual', 'Infinity', 'Pi', 'Sigma', 'Omega',
      'AlignLeft', 'AlignCenter', 'AlignRight', 'AlignJustify',
      'AlignStartHorizontal', 'AlignStartVertical', 'AlignEndHorizontal', 'AlignEndVertical',
      'AlignCenterHorizontal', 'AlignCenterVertical',
      'FoldHorizontal', 'FoldVertical', 'UnfoldHorizontal', 'UnfoldVertical',
    ]
  },
  {
    key: 'communication',
    name: '通讯',
    icons: [
      'Mail', 'MailOpen', 'MailCheck', 'MailX', 'MailQuestion', 'MailWarning',
      'MailPlus', 'MailMinus', 'Mails', 'Inbox', 'Send', 'SendHorizontal',
      'MessageSquare', 'MessageCircle', 'MessageSquareDashed', 'MessageSquarePlus',
      'MessageSquareMinus', 'MessageSquareX', 'MessageSquareWarning', 'MessageSquareQuote',
      'MessageSquareReply', 'MessageSquareShare', 'MessageSquareMore', 'MessageSquareLock',
      'MessageSquareHeart', 'MessageSquareOff', 'MessageSquareDiff',
      'MessagesSquare', 'MessageCircleDashed', 'MessageCirclePlus', 'MessageCircleMinus',
      'MessageCircleX', 'MessageCircleWarning', 'MessageCircleQuote', 'MessageCircleReply',
      'MessageCircleShare', 'MessageCircleMore', 'MessageCircleLock', 'MessageCircleHeart',
      'MessageCircleOff', 'MessageCircleCode', 'MessagesCircle',
      'Phone', 'PhoneCall', 'PhoneForwarded', 'PhoneIncoming', 'PhoneMissed',
      'PhoneOff', 'PhoneOutgoing', 'Smartphone', 'SmartphoneNfc', 'SmartphoneCharging',
      'Tablet', 'TabletSmartphone', 'Watch', 'Contact', 'Contact2',
      'Share', 'Share2', 'Network', 'Radio', 'RadioReceiver', 'RadioTower',
      'Satellite', 'SatelliteDish', 'Antenna', 'Nfc',
      'Video', 'VideoOff', 'VideoIcon', 'Voicemail', 'VoicemailIcon',
      'AtSign', 'Hash', 'Link', 'Link2', 'Unlink', 'Unlink2',
      'Paperclip', 'PaperclipIcon', 'Quote', 'QuoteIcon',
    ]
  },
  {
    key: 'design',
    name: '设计',
    icons: [
      'Palette', 'Paintbrush', 'Paintbrush2', 'PaintBucket', 'PaintRoller',
      'Pen', 'PenTool', 'Pencil', 'PencilLine', 'PencilRuler', 'Highlighter',
      'Marker', 'Brush', 'Eraser', 'Scissors', 'ScissorsSquare',
      'Type', 'TypeOutline', 'Bold', 'Italic', 'Underline', 'Strikethrough',
      'RemoveFormatting', 'Text', 'TextCursor', 'TextCursorInput',
      'TextSelect', 'TextQuote', 'TextSearch', 'TextIcon',
      'Asterisk', 'AsteriskSquare', 'HashIcon',
      'AlignLeft', 'AlignCenter', 'AlignRight', 'AlignJustify',
      'AlignVerticalDistributeCenter', 'AlignVerticalDistributeEnd', 'AlignVerticalDistributeStart',
      'AlignHorizontalDistributeCenter', 'AlignHorizontalDistributeEnd', 'AlignHorizontalDistributeStart',
      'AlignVerticalJustifyCenter', 'AlignVerticalJustifyEnd', 'AlignVerticalJustifyStart',
      'AlignHorizontalJustifyCenter', 'AlignHorizontalJustifyEnd', 'AlignHorizontalJustifyStart',
      'AlignStartVertical', 'AlignEndVertical', 'AlignStartHorizontal', 'AlignEndHorizontal',
      'AlignCenterVertical', 'AlignCenterHorizontal',
      'Grid3x3', 'Grid2x2', 'Grid3x2', 'Grid2x3', 'LayoutGrid', 'LayoutTemplate',
      'LayoutList', 'LayoutDashboard', 'LayoutPanelLeft', 'LayoutPanelTop',
      'Columns2', 'Columns3', 'Columns4', 'Rows2', 'Rows3', 'Rows4',
      'PanelLeft', 'PanelRight', 'PanelTop', 'PanelBottom', 'PanelLeftClose', 'PanelLeftOpen',
      'PanelRightClose', 'PanelRightOpen', 'PanelTopClose', 'PanelTopOpen',
      'PanelBottomClose', 'PanelBottomOpen',
      'Square', 'SquareDashed', 'SquareDot', 'SquareStack', 'SquareEqual',
      'SquareAsterisk', 'SquareCheck', 'SquareChevronDown', 'SquareChevronLeft',
      'SquareChevronRight', 'SquareChevronUp', 'SquareCode', 'SquareDivide',
      'SquareFunction', 'SquareKanban', 'SquareM', 'SquareMenu', 'SquareMinus',
      'SquareMousePointer', 'SquareParking', 'SquareParkingOff', 'SquarePen',
      'SquarePercent', 'SquarePi', 'SquarePilcrow', 'SquarePlus', 'SquarePower',
      'SquareRadical', 'SquareScissors', 'SquareSigma', 'SquareSlash', 'SquareSplitHorizontal',
      'SquareSplitVertical', 'SquareSquare', 'SquareTerminal', 'SquareUser', 'SquareX',
      'Circle', 'CircleDashed', 'CircleDot', 'CircleDotted', 'CircleEllipsis',
      'CircleEqual', 'CircleOff', 'CircleSlash', 'CircleSlash2',
      'Triangle', 'TriangleRight', 'TriangleAlert', 'TriangleDashed',
      'Diamond', 'DiamondPercent', 'Octagon', 'OctagonAlert', 'OctagonX',
      'Hexagon', 'Pentagon', 'Star', 'Sparkles', 'Wand', 'Wand2',
      'FlipHorizontal', 'FlipHorizontal2', 'FlipVertical', 'FlipVertical2',
      'Rotate3d', 'RotateCcwSquare', 'RotateCwSquare',
      'Scan', 'ScanFace', 'ScanEye', 'ScanLine', 'ScanSearch', 'ScanText',
      'Focus', 'FocusIcon',
      'Layers', 'Layers2', 'Layers3', 'Stack', 'Group',
      'Ungroup', 'UngroupIcon',
      'Combine', 'Split', 'Merge', 'Diff', 'GitCompare', 'GitMerge',
      'GitPullRequest', 'GitPullRequestClosed', 'GitPullRequestDraft',
      'GitCommitHorizontal', 'GitCommitVertical', 'GitBranch', 'GitFork',
      'GitGraph', 'GitMergeIcon', 'GitPullRequestArrow', 'GitPullRequestCreate',
      'GitPullRequestCreateArrow',
    ]
  },
  {
    key: 'development',
    name: '开发',
    icons: [
      'Code', 'Code2', 'CodeXml', 'Codepen', 'Codesandbox', 'Terminal',
      'TerminalSquare', 'Command', 'Keyboard', 'KeyboardIcon',
      'Bug', 'BugOff', 'BugPlay', 'FileCode', 'FileCode2', 'FileJson',
      'FileType', 'FileType2', 'FileTerminal', 'FileDigit',
      'Braces', 'Brackets', 'Parentheses', 'CurlyBraces',
      'ChevronsLeftRight', 'ChevronsRightLeft', 'ChevronsUpDown',
      'Quote', 'QuoteIcon', 'QuoteSquare',
      'Hash', 'AtSign', 'DollarSign', 'Percent', 'Ampersand', 'Asterisk',
      'Plus', 'Minus', 'Divide', 'Equal', 'NotEqual',
      'Variable', 'FunctionSquare', 'Sigma', 'Pi', 'Omega',
      'Binary', 'CircuitBoard', 'Cpu', 'HardDrive', 'HardDriveDownload',
      'HardDriveUpload', 'Database', 'DatabaseBackup', 'DatabaseZap',
      'Server', 'ServerOff', 'ServerCog', 'ServerCrash', 'ServerIcon',
      'Cloud', 'CloudOff', 'CloudDownload', 'CloudUpload', 'CloudRain',
      'CloudRainWind', 'CloudSnow', 'CloudLightning', 'CloudFog', 'CloudHail',
      'CloudMoon', 'CloudSun', 'Cloudy',
      'Container', 'Docker', 'Webhook', 'WebhooksIcon',
      'GitBranch', 'GitCommitHorizontal', 'GitCommitVertical', 'GitCompare',
      'GitFork', 'GitGraph', 'GitMerge', 'GitPullRequest', 'GitPullRequestClosed',
      'GitPullRequestDraft', 'GitPullRequestArrow', 'GitPullRequestCreate',
      'GitPullRequestCreateArrow',
      'Github', 'Gitlab', 'Chrome', 'Safari', 'Firefox', 'Edge',
      'Figma', 'Framer', 'Trello', 'Jira', 'Slack', 'Discord',
      'Npm', 'Yarn', 'Pnpm',
      'Aperture', 'Atom', 'AtomIcon', 'Blocks', 'Box', 'BoxSelect',
      'ContainerIcon', 'Cuboid', 'Cylinder', 'DiamondIcon', 'Dna',
      'DnaOff', 'HexagonIcon', 'Layers', 'OctagonIcon', 'PentagonIcon',
      'Pyramid', 'Sphere', 'SquareIcon', 'Torus', 'TriangleIcon',
    ]
  },
  {
    key: 'documents',
    name: '文档',
    icons: [
      'File', 'FileAxis3d', 'FileBadge', 'FileBadge2', 'FileBarChart',
      'FileBarChart2', 'FileBox', 'FileCheck', 'FileCheck2', 'FileClock',
      'FileCode', 'FileCode2', 'FileCog', 'FileDiff', 'FileDigit',
      'FileDown', 'FileEdit', 'FileHeart', 'FileImage', 'FileInput',
      'FileJson', 'FileKey', 'FileKey2', 'FileLineChart', 'FileLock',
      'FileLock2', 'FileMinus', 'FileMinus2', 'FileMusic', 'FileOutput',
      'FilePieChart', 'FilePlus', 'FilePlus2', 'FileQuestion', 'FileScan',
      'FileSearch', 'FileSearch2', 'FileSignature', 'FileSpreadsheet',
      'FileStack', 'FileSymlink', 'FileTerminal', 'FileText', 'FileType',
      'FileType2', 'FileUp', 'FileVideo', 'FileVideo2', 'FileVolume',
      'FileVolume2', 'FileWarning', 'FileX', 'FileX2', 'Files',
      'Folder', 'FolderArchive', 'FolderCheck', 'FolderClock', 'FolderClosed',
      'FolderCog', 'FolderDot', 'FolderDown', 'FolderGit', 'FolderGit2',
      'FolderHeart', 'FolderInput', 'FolderKanban', 'FolderKey', 'FolderLock',
      'FolderMinus', 'FolderOpen', 'FolderOpenDot', 'FolderOutput',
      'FolderPen', 'FolderPlus', 'FolderRoot', 'FolderSearch', 'FolderSearch2',
      'FolderSymlink', 'FolderSync', 'FolderTree', 'FolderUp', 'FolderX',
      'Folders',
      'ScrollText', 'Scroll', 'Book', 'BookA', 'BookAudio', 'BookCheck',
      'BookCopy', 'BookDashed', 'BookDown', 'BookHeadphones', 'BookHeart',
      'BookImage', 'BookKey', 'BookLock', 'BookMarked', 'BookMinus',
      'BookOpen', 'BookOpenCheck', 'BookOpenText', 'BookPlus', 'BookText',
      'BookType', 'BookUp', 'BookUp2', 'BookUser', 'BookX',
      'Bookmark', 'BookmarkCheck', 'BookmarkMinus', 'BookmarkPlus', 'BookmarkX',
      'Library', 'LibrarySquare', 'Notebook', 'NotebookPen', 'NotebookTabs',
      'NotebookText', 'StickyNote',
      'Clipboard', 'ClipboardCheck', 'ClipboardCopy', 'ClipboardEdit',
      'ClipboardList', 'ClipboardMinus', 'ClipboardPaste', 'ClipboardPlus',
      'ClipboardSignature', 'ClipboardType', 'ClipboardX',
      'Copy', 'CopyCheck', 'CopyMinus', 'CopyPlus', 'CopyX', 'Copyleft',
      'Copyright', 'CreativeCommons',
      'Text', 'TextCursor', 'TextCursorInput', 'TextSelect', 'TextSearch',
      'Type', 'TypeOutline', 'AlignLeft', 'AlignCenter', 'AlignRight',
      'AlignJustify', 'List', 'ListCheck', 'ListChecks', 'ListCollapse',
      'ListEnd', 'ListFilter', 'ListMinus', 'ListMusic', 'ListOrdered',
      'ListPlus', 'ListRestart', 'ListStart', 'ListTodo', 'ListTree',
      'ListVideo', 'ListX',
      'Paperclip', 'PaperclipIcon', 'Attachment', 'Link', 'Link2',
      'Unlink', 'Unlink2', 'Quote', 'QuoteIcon',
      'Printer', 'PrinterCheck', 'PrinterIcon', 'Scan', 'ScanLine',
      'ScanFace', 'ScanEye', 'ScanSearch', 'ScanText',
      'Newspaper', 'Sheet', 'Table', 'Table2', 'TableCellsMerge',
      'TableCellsSplit', 'TableColumnsSplit', 'TableProperties', 'TableRowsSplit',
      'Grid3x3', 'Grid2x2', 'LayoutGrid', 'LayoutList', 'LayoutTemplate',
      'LayoutDashboard', 'LayoutPanelLeft', 'LayoutPanelTop',
    ]
  },
  {
    key: 'media',
    name: '媒体',
    icons: [
      'Image', 'ImageDown', 'ImageIcon', 'ImageMinus', 'ImageOff', 'ImagePlay',
      'ImagePlus', 'ImageUp', 'Images', 'PictureInPicture', 'PictureInPicture2',
      'GalleryHorizontal', 'GalleryHorizontalEnd', 'GalleryThumbnails',
      'GalleryVertical', 'GalleryVerticalEnd',
      'Camera', 'CameraOff', 'CameraIcon',
      'Video', 'VideoOff', 'VideoIcon', 'Film', 'Clapperboard',
      'Play', 'PlayCircle', 'Pause', 'PauseCircle', 'PauseOctagon',
      'StopCircle', 'SkipBack', 'SkipForward', 'StepBack', 'StepForward',
      'FastForward', 'Rewind', 'Repeat', 'Repeat1', 'Repeat2',
      'Shuffle', 'Volume', 'Volume1', 'Volume2', 'VolumeX', 'VolumeOff',
      'Mic', 'Mic2', 'MicOff', 'Headphones', 'HeadphoneOff',
      'Music', 'Music2', 'Music3', 'Music4', 'Radio', 'RadioReceiver',
      'RadioTower', 'Podcast', 'Disc', 'Disc2', 'Disc3', 'Album',
      'Monitor', 'MonitorDot', 'MonitorDown', 'MonitorOff', 'MonitorPause',
      'MonitorPlay', 'MonitorSmartphone', 'MonitorSpeaker', 'MonitorStop',
      'MonitorUp', 'MonitorX', 'Tv', 'Tv2', 'TvIcon', 'Projector',
      'Smartphone', 'Tablet', 'TabletSmartphone', 'Laptop', 'Laptop2',
      'Computer', 'Cpu', 'HardDrive', 'HardDriveDownload', 'HardDriveUpload',
      'Keyboard', 'KeyboardIcon', 'Mouse', 'MousePointer', 'MousePointer2',
      'MousePointerClick', 'Scan', 'ScanFace', 'ScanEye', 'ScanLine',
      'ScanSearch', 'ScanText', 'QrCode', 'Barcode', 'Rss', 'Signal',
      'SignalHigh', 'SignalLow', 'SignalMedium', 'SignalZero',
      'Wifi', 'WifiOff', 'WifiHigh', 'WifiLow', 'WifiZero',
      'Bluetooth', 'BluetoothConnected', 'BluetoothOff', 'BluetoothSearching',
      'Airplay', 'Cast', 'Chromecast', 'ScreenShare', 'ScreenShareOff',
      'Presentation', 'ProjectorIcon', 'Slideshow', 'PresentationIcon',
      'Sun', 'Moon', 'MoonStar', 'Star', 'StarOff', 'Sparkles',
      'SunDim', 'SunMedium', 'SunMoon', 'SunSnowflake',
    ]
  },
  {
    key: 'navigation',
    name: '导航',
    icons: [
      'Menu', 'MenuSquare', 'MenuIcon',
      'Home', 'HomeIcon',
      'Building', 'Building2', 'Castle', 'Church', 'School', 'Hotel',
      'Store', 'Warehouse', 'Hospital', 'Landmark', 'LandmarkIcon',
      'Navigation', 'Navigation2', 'NavigationOff', 'Navigation2Off',
      'Compass', 'Map', 'MapPin', 'MapPinned', 'MapPinOff',
      'Globe', 'Globe2', 'GlobeIcon', 'Earth', 'EarthLock',
      'Plane', 'PlaneTakeoff', 'PlaneLanding', 'PlaneIcon',
      'Car', 'CarFront', 'CarTaxiFront', 'Bus', 'BusFront',
      'Train', 'TrainFront', 'TrainFrontTunnel', 'TrainTrack',
      'TramFront', 'Ship', 'ShipIcon', 'Sailboat', 'SailboatIcon',
      'Bike', 'BikeIcon', 'Footprints', 'FootprintsIcon',
      'Flag', 'FlagOff', 'FlagTriangleLeft', 'FlagTriangleRight',
      'FlagIcon', 'Milestone', 'MilestoneIcon', 'Signpost', 'SignpostBig',
      'SignpostIcon', 'TrafficCone', 'TrafficConeIcon',
      'Locate', 'LocateFixed', 'LocateOff', 'Radar', 'RadarIcon',
      'Crosshair', 'Target', 'Focus', 'FocusIcon', 'ScanEye',
      'Search', 'SearchIcon', 'SearchX', 'SearchCheck', 'SearchCode',
      'SearchSlash', 'ZoomIn', 'ZoomOut',
      'Bookmark', 'BookmarkCheck', 'BookmarkMinus', 'BookmarkPlus', 'BookmarkX',
      'BookMarked', 'Pin', 'PinOff', 'Thumbtack',
      'Link', 'Link2', 'Unlink', 'Unlink2', 'ExternalLink', 'ExternalLinkIcon',
      'Share', 'Share2', 'ShareIcon', 'Send', 'SendHorizontal', 'Forward',
      'Reply', 'ReplyAll', 'ReplyIcon', 'ReplyAllIcon',
      'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight',
      'ArrowUpLeft', 'ArrowUpRight', 'ArrowDownLeft', 'ArrowDownRight',
      'ChevronUp', 'ChevronDown', 'ChevronLeft', 'ChevronRight',
      'ChevronsUp', 'ChevronsDown', 'ChevronsLeft', 'ChevronsRight',
    ]
  },
  {
    key: 'notifications',
    name: '通知',
    icons: [
      'Bell', 'BellDot', 'BellElectric', 'BellMinus', 'BellOff', 'BellPlus',
      'BellRing', 'BellIcon',
      'Megaphone', 'MegaphoneOff', 'Speaker', 'SpeakerIcon',
      'Volume', 'Volume1', 'Volume2', 'VolumeX', 'VolumeOff',
      'AlertCircle', 'AlertTriangle', 'AlertOctagon', 'AlertOctagonIcon',
      'Info', 'InfoIcon', 'HelpCircle', 'HelpCircleIcon',
      'XCircle', 'CheckCircle', 'MinusCircle', 'PlusCircle',
      'XSquare', 'CheckSquare', 'MinusSquare', 'PlusSquare',
      'X', 'Check', 'Minus', 'Plus', 'Slash',
      'CircleAlert', 'CircleCheck', 'CircleDashed', 'CircleDot',
      'CircleDotDashed', 'CircleEllipsis', 'CircleEqual', 'CircleOff',
      'CircleSlash', 'CircleSlash2', 'CircleUser', 'CircleX',
      'SquareAlert', 'SquareCheck', 'SquareDashed', 'SquareDot',
      'SquareEqual', 'SquareMinus', 'SquareOff', 'SquarePlus',
      'SquareSlash', 'SquareUser', 'SquareX',
      'TriangleAlert', 'OctagonAlert', 'OctagonX', 'OctagonIcon',
      'Shield', 'ShieldAlert', 'ShieldCheck', 'ShieldEllipsis',
      'ShieldHalf', 'ShieldMinus', 'ShieldOff', 'ShieldPlus', 'ShieldQuestion',
      'ShieldX', 'ShieldIcon',
      'Badge', 'BadgeAlert', 'BadgeCheck', 'BadgeHelp', 'BadgeInfo',
      'BadgeMinus', 'BadgePercent', 'BadgePlus', 'BadgeX', 'BadgeIcon',
      'Banner', 'Flag', 'FlagOff', 'FlagTriangleLeft', 'FlagTriangleRight',
      'Mail', 'MailOpen', 'MailCheck', 'MailX', 'MailQuestion', 'MailWarning',
      'MailPlus', 'MailMinus', 'Mails', 'Inbox', 'Send', 'SendHorizontal',
      'MessageSquare', 'MessageSquareDashed', 'MessageSquarePlus',
      'MessageSquareMinus', 'MessageSquareX', 'MessageSquareWarning',
      'MessageSquareReply', 'MessageSquareShare', 'MessageSquareMore',
      'MessageSquareLock', 'MessageSquareHeart', 'MessageSquareOff',
      'MessageSquareDiff', 'MessagesSquare',
      'MessageCircle', 'MessageCircleDashed', 'MessageCirclePlus',
      'MessageCircleMinus', 'MessageCircleX', 'MessageCircleWarning',
      'MessageCircleReply', 'MessageCircleShare', 'MessageCircleMore',
      'MessageCircleLock', 'MessageCircleHeart', 'MessageCircleOff',
      'MessageCircleCode', 'MessagesCircle',
      'Sparkles', 'Zap', 'ZapOff', 'Flame', 'FlameKindling',
      'FlameIcon', 'FireExtinguisher',
    ]
  },
  {
    key: 'shapes',
    name: '形状',
    icons: [
      'Square', 'SquareDashed', 'SquareDot', 'SquareStack', 'SquareEqual',
      'SquareAsterisk', 'SquareCheck', 'SquareChevronDown', 'SquareChevronLeft',
      'SquareChevronRight', 'SquareChevronUp', 'SquareCode', 'SquareDivide',
      'SquareFunction', 'SquareKanban', 'SquareM', 'SquareMenu', 'SquareMinus',
      'SquareMousePointer', 'SquareParking', 'SquareParkingOff', 'SquarePen',
      'SquarePercent', 'SquarePi', 'SquarePilcrow', 'SquarePlus', 'SquarePower',
      'SquareRadical', 'SquareScissors', 'SquareSigma', 'SquareSlash',
      'SquareSplitHorizontal', 'SquareSplitVertical', 'SquareSquare',
      'SquareTerminal', 'SquareUser', 'SquareX',
      'Circle', 'CircleDashed', 'CircleDot', 'CircleDotted', 'CircleEllipsis',
      'CircleEqual', 'CircleOff', 'CircleSlash', 'CircleSlash2',
      'CircleAlert', 'CircleArrowDown', 'CircleArrowLeft', 'CircleArrowRight',
      'CircleArrowUp', 'CircleArrowUpLeft', 'CircleArrowUpRight',
      'CircleArrowDownLeft', 'CircleArrowDownRight', 'CircleCheck',
      'CircleCheckBig', 'CircleChevronDown', 'CircleChevronLeft',
      'CircleChevronRight', 'CircleChevronUp', 'CircleDivide', 'CircleDollarSign',
      'CircleDotDashed', 'CircleFadingArrowUp', 'CircleFadingPlus',
      'CircleGauge', 'CircleHelp', 'CircleMinus', 'CircleParking',
      'CircleParkingOff', 'CirclePause', 'CirclePercent', 'CirclePlay',
      'CirclePlus', 'CirclePower', 'CircleSlash2', 'CircleStop', 'CircleUser',
      'CircleUserRound', 'CircleX',
      'Triangle', 'TriangleRight', 'TriangleAlert', 'TriangleDashed',
      'Diamond', 'DiamondPercent', 'Octagon', 'OctagonAlert', 'OctagonX',
      'OctagonPause', 'Hexagon', 'Pentagon', 'Star', 'StarOff', 'Sparkle',
      'Sparkles', 'Heart', 'HeartCrack', 'HeartHandshake', 'HeartIcon',
      'HeartOff', 'HeartPulse', 'Hearts',
      'Annoyed', 'AnnoyedIcon', 'Frown', 'FrownIcon', 'Laugh', 'LaughIcon',
      'Meh', 'MehIcon', 'Smile', 'SmileIcon', 'SmilePlus',
      'Ghost', 'GhostIcon', 'Skull', 'SkullIcon',
      'Anchor', 'AnchorIcon', 'Cone', 'ConeIcon', 'Cube', 'Cuboid',
      'Cylinder', 'Pyramid', 'Sphere', 'Torus',
      'Asterisk', 'AsteriskSquare', 'AsteriskIcon',
      'Cross', 'CrossIcon', 'X', 'Check', 'Minus', 'Plus',
      'Divide', 'Percent', 'Equal', 'NotEqual',
      'Infinity', 'Pi', 'Sigma', 'Omega',
    ]
  },
  {
    key: 'system',
    name: '系统',
    icons: [
      'Settings', 'Settings2', 'Cog', 'CogIcon', 'SlidersHorizontal',
      'SlidersVertical', 'ToggleLeft', 'ToggleRight', 'ToggleIcon',
      'Power', 'PowerOff', 'PowerIcon', 'Plug', 'Plug2', 'PlugZap',
      'PlugZap2', 'Unplug', 'Unplug2',
      'Battery', 'BatteryCharging', 'BatteryFull', 'BatteryLow',
      'BatteryMedium', 'BatteryWarning', 'BatteryIcon',
      'Wifi', 'WifiOff', 'WifiHigh', 'WifiLow', 'WifiZero',
      'Bluetooth', 'BluetoothConnected', 'BluetoothOff', 'BluetoothSearching',
      'Signal', 'SignalHigh', 'SignalLow', 'SignalMedium', 'SignalZero',
      'Radio', 'RadioReceiver', 'RadioTower', 'Antenna',
      'Cpu', 'HardDrive', 'HardDriveDownload', 'HardDriveUpload',
      'Database', 'DatabaseBackup', 'DatabaseZap', 'Server', 'ServerOff',
      'ServerCog', 'ServerCrash', 'ServerIcon',
      'Cloud', 'CloudOff', 'CloudDownload', 'CloudUpload', 'CloudRain',
      'CloudRainWind', 'CloudSnow', 'CloudLightning', 'CloudFog', 'CloudHail',
      'CloudMoon', 'CloudSun', 'Cloudy',
      'Sun', 'Moon', 'MoonStar', 'Star', 'StarOff', 'Sparkles',
      'SunDim', 'SunMedium', 'SunMoon', 'SunSnowflake',
      'Thermometer', 'ThermometerSnowflake', 'ThermometerSun',
      'Droplets', 'Droplet', 'DropletOff', 'Umbrella', 'UmbrellaOff',
      'Wind', 'Fan', 'AirVent', 'AirConditioning',
      'Gauge', 'GaugeCircle', 'Activity', 'ActivitySquare',
      'Pulse', 'HeartPulse', 'HeartCrack', 'HeartHandshake',
      'Timer', 'TimerOff', 'TimerReset', 'TimerIcon', 'Clock',
      'Clock1', 'Clock2', 'Clock3', 'Clock4', 'Clock5', 'Clock6',
      'Clock7', 'Clock8', 'Clock9', 'Clock10', 'Clock11', 'Clock12',
      'AlarmClock', 'AlarmClockCheck', 'AlarmClockMinus', 'AlarmClockOff',
      'AlarmClockPlus', 'Stopwatch', 'Hourglass', 'Calendar',
      'CalendarCheck', 'CalendarCheck2', 'CalendarClock', 'CalendarDays',
      'CalendarFold', 'CalendarHeart', 'CalendarMinus', 'CalendarOff',
      'CalendarPlus', 'CalendarRange', 'CalendarSearch', 'CalendarX',
      'CalendarX2', 'CalendarIcon',
      'History', 'HistoryIcon', 'RotateCcw', 'RotateCw', 'RefreshCcw',
      'RefreshCw', 'Repeat', 'Repeat1', 'Repeat2',
      'Undo', 'Undo2', 'Redo', 'Redo2', 'Reply', 'ReplyAll',
      'Forward', 'StepBack', 'StepForward', 'SkipBack', 'SkipForward',
      'Play', 'Pause', 'Square', 'Circle', 'Octagon',
      'Maximize', 'Maximize2', 'Minimize', 'Minimize2', 'MaximizeIcon',
      'Fullscreen', 'FullscreenIcon',
      'PanelLeft', 'PanelRight', 'PanelTop', 'PanelBottom',
      'PanelLeftClose', 'PanelLeftOpen', 'PanelRightClose', 'PanelRightOpen',
      'PanelTopClose', 'PanelTopOpen', 'PanelBottomClose', 'PanelBottomOpen',
      'Sidebar', 'SidebarClose', 'SidebarOpen', 'SidebarIcon',
      'LayoutGrid', 'LayoutList', 'LayoutTemplate', 'LayoutDashboard',
      'LayoutPanelLeft', 'LayoutPanelTop',
      'AppWindow', 'AppWindowMac', 'AppWindowIcon',
      'Command', 'CommandIcon', 'Terminal', 'TerminalSquare',
      'Keyboard', 'KeyboardIcon', 'Mouse', 'MousePointer', 'MousePointer2',
      'MousePointerClick', 'Scan', 'ScanLine', 'ScanFace', 'ScanEye',
      'ScanSearch', 'ScanText', 'Fingerprint', 'Eye', 'EyeOff',
      'EyeIcon', 'Glasses', 'GlassesIcon',
      'Lock', 'LockIcon', 'LockKeyhole', 'LockKeyholeIcon',
      'Unlock', 'UnlockIcon', 'UnlockKeyhole', 'UnlockKeyholeIcon',
      'Key', 'KeyRound', 'KeySquare', 'Shield', 'ShieldAlert',
      'ShieldCheck', 'ShieldEllipsis', 'ShieldHalf', 'ShieldMinus',
      'ShieldOff', 'ShieldPlus', 'ShieldQuestion', 'ShieldX', 'ShieldIcon',
      'Siren', 'SirenIcon', 'AlertTriangle', 'AlertCircle', 'AlertOctagon',
      'HelpCircle', 'Info', 'XCircle', 'CheckCircle', 'MinusCircle', 'PlusCircle',
    ]
  },
  {
    key: 'users',
    name: '用户',
    icons: [
      'User', 'User2', 'UserCheck', 'UserCheck2', 'UserCircle', 'UserCircle2',
      'UserCog', 'UserCog2', 'UserMinus', 'UserMinus2', 'UserPlus', 'UserPlus2',
      'UserRound', 'UserRoundCheck', 'UserRoundCog', 'UserRoundMinus',
      'UserRoundPlus', 'UserRoundSearch', 'UserRoundX', 'UserRoundIcon',
      'UserSearch', 'UserX', 'UserX2', 'Users', 'Users2', 'UsersRound',
      'Contact', 'Contact2', 'ContactIcon',
      'IdCard', 'Fingerprint', 'ScanFace', 'ScanEye',
      'Smile', 'Frown', 'Meh', 'Laugh', 'Annoyed',
      'UserIcon', 'UsersIcon', 'UserSquare', 'UserSquare2',
      'CircleUser', 'CircleUserRound', 'SquareUser',
      'PersonStanding', 'Baby', 'Accessibility', 'AccessibilityIcon',
      'Armchair', 'Bed', 'BedDouble', 'BedSingle', 'Bath',
      'Crown', 'Gem', 'Gift', 'HeartHandshake', 'HeartIcon',
      'Handshake', 'HandshakeIcon', 'HelpingHand', 'HelpingHandIcon',
      'Key', 'KeyRound', 'KeySquare', 'Lock', 'Unlock',
      'Eye', 'EyeOff', 'Glasses', 'ScanFace', 'Fingerprint',
      'VenetianMask', 'VenetianMaskIcon', 'Theater', 'Drama',
      'GraduationCap', 'School', 'School2', 'SchoolIcon',
      'Briefcase', 'BriefcaseBusiness', 'BriefcaseMedical', 'BriefcaseIcon',
      'Building', 'Building2', 'Castle', 'Church', 'Hotel',
      'Store', 'Warehouse', 'Hospital', 'Landmark', 'LandmarkIcon',
      'Home', 'HomeIcon',
    ]
  },
]

/**
 * 默认分类键列表
 */
export const DEFAULT_CATEGORIES = ICON_CATEGORIES.map(cat => cat.key)

/**
 * 获取分类名称
 * @param key - 分类键
 * @returns 分类名称
 */
export function getCategoryName(key: string): string {
  const category = ICON_CATEGORIES.find(cat => cat.key === key)
  return category?.name || key
}

/**
 * 获取所有图标名称列表
 * @returns 图标名称数组
 */
export function getAllIconNames(): string[] {
  return ICON_CATEGORIES.flatMap(cat => cat.icons)
}
